---
# meta/main.yml - Meta information for the logging role

galaxy_info:
  role_name: logging
  author: SOE Team
  description: Configures logging and auditing for SOE
  company: SOE Team
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: EL
      versions:
        - 7
        - 8
        - 9
    - name: Debian
      versions:
        - buster
        - bullseye
    - name: Ubuntu
      versions:
        - focal
        - jammy

  galaxy_tags:
    - logging
    - security
    - auditd
    - rsyslog
    - soe

dependencies: []