- name: RHEL9 SOE Configuration
  hosts: all
  become: true
  collections:
    - ansible.posix
    - community.general
    - community.crypto
    - ansible.utils
    - ansible.builtin
  roles:
    - luks_encryption
    - ad_join
    - azure_backup
    - chrony
    - common
    - fapolicyd
    - librenms
    - logging
    - login_banner
    - defender_endpoint
    - security
    - system_update 
    - veeam
    - yubikey 