---
# handlers/main.yml - Handlers for logging role

- name: Restart rsyslog
  ansible.builtin.service:
    name: "{{ service_names.rsyslog[ansible_os_family] }}"
    state: restarted

- name: Restart auditd
  ansible.builtin.service:
    name: "{{ service_names.auditd[ansible_os_family] }}"
    state: restarted

- name: Load audit rules
  ansible.builtin.command: augenrules --load
  changed_when: true

- name: Update grub
  ansible.builtin.command: "{{ grub_update_cmd[ansible_os_family][ansible_distribution_major_version] | default(grub_update_cmd[ansible_os_family][ansible_distribution_release] | default('grub2-mkconfig -o /boot/grub2/grub.cfg')) }}"
  changed_when: true